name: training-kafka-streams-src
lang: unknown
lang_version: unknown
git:
  enable: true
github:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
renovatebot:
  enable: false